#swagger: '2.0'
#info:
#  title: Cloud Endpoints + GCF
#  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
#  version: 1.0.0
#host: democloudrun-ss6kk56qzq-an.a.run.app
#schemes:
#  - https
#produces:
#  - application/json
#paths:
#  /hello:
#    get:
#      summary: Greet a user
#      operationId: hello
#      x-google-backend:
#        address: https://asia-northeast1-stellar-arcadia-332908.cloudfunctions.net/helloPOST
#        protocol: h2
#      responses:
#        '200':
#          description: A successful response
#          schema:
#            type: string